package model;

// Generated 11/12/2013 01:39:05 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * EspecialidadesMedicas2011 generated by hbm2java
 */
@Entity
@Table(name = "especialidades_medicas_2011", catalog = "saude_rec")
public class EspecialidadesMedicas2011 implements java.io.Serializable {

	private EspecialidadesMedicas2011Id id;

	public EspecialidadesMedicas2011() {
	}

	public EspecialidadesMedicas2011(EspecialidadesMedicas2011Id id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "hospitalCodigo", column = @Column(name = "HOSPITAL_CODIGO")),
			@AttributeOverride(name = "especialidadeCodigo", column = @Column(name = "ESPECIALIDADE_CODIGO")),
			@AttributeOverride(name = "especialidadeDescricao", column = @Column(name = "ESPECIALIDADE_DESCRICAO", length = 20)) })
	public EspecialidadesMedicas2011Id getId() {
		return this.id;
	}

	public void setId(EspecialidadesMedicas2011Id id) {
		this.id = id;
	}

}
