package model;

// Generated 14/12/2013 01:12:12 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * EspecialidadesMedicas2012 generated by hbm2java
 */
@Entity
@Table(name = "especialidades_medicas_2012", catalog = "saude_rec")
public class EspecialidadesMedicas2012 implements java.io.Serializable {

	private EspecialidadesMedicas2012Id id;

	public EspecialidadesMedicas2012() {
	}

	public EspecialidadesMedicas2012(EspecialidadesMedicas2012Id id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "hospitalCodigo", column = @Column(name = "HOSPITAL_CODIGO")),
			@AttributeOverride(name = "especialidadeCodigo", column = @Column(name = "ESPECIALIDADE_CODIGO")),
			@AttributeOverride(name = "especialidadeDescricao", column = @Column(name = "ESPECIALIDADE_DESCRICAO", length = 20)) })
	public EspecialidadesMedicas2012Id getId() {
		return this.id;
	}

	public void setId(EspecialidadesMedicas2012Id id) {
		this.id = id;
	}

}
