package model;

// Generated 11/12/2013 01:39:05 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Hospitais2013 generated by hbm2java
 */
@Entity
@Table(name = "hospitais_2013", catalog = "saude_rec")
public class Hospitais2013 implements java.io.Serializable {

	private Hospitais2013Id id;

	public Hospitais2013() {
	}

	public Hospitais2013(Hospitais2013Id id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "hospitalCodigo", column = @Column(name = "HOSPITAL_CODIGO")),
			@AttributeOverride(name = "hospitalNome", column = @Column(name = "HOSPITAL_NOME", length = 50)),
			@AttributeOverride(name = "bairrosaudeCodigo", column = @Column(name = "BAIRROSAUDE_CODIGO")) })
	public Hospitais2013Id getId() {
		return this.id;
	}

	public void setId(Hospitais2013Id id) {
		this.id = id;
	}

}
