package model;

// Generated 27/01/2014 15:23:40 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * RankingBairros generated by hbm2java
 */
@Entity
@Table(name = "ranking_bairros", catalog = "saude_rec")
public class RankingBairros implements java.io.Serializable {

	private RankingBairrosId id;

	public RankingBairros() {
	}

	public RankingBairros(RankingBairrosId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "posicao", column = @Column(name = "posicao", length = 4)),
			@AttributeOverride(name = "codigoBairro", column = @Column(name = "codigo_bairro", length = 10)),
			@AttributeOverride(name = "numeroChamados", column = @Column(name = "numero_chamados", length = 10)),
			@AttributeOverride(name = "nomeBairro", column = @Column(name = "nome_bairro", length = 100)) })
	public RankingBairrosId getId() {
		return this.id;
	}

	public void setId(RankingBairrosId id) {
		this.id = id;
	}

}
