package model;

// Generated 27/01/2014 15:23:40 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RankingBairrosId generated by hbm2java
 */
@Embeddable
public class RankingBairrosId implements java.io.Serializable {

	private String posicao;
	private String codigoBairro;
	private String numeroChamados;
	private String nomeBairro;

	public RankingBairrosId() {
	}

	public RankingBairrosId(String posicao, String codigoBairro,
			String numeroChamados, String nomeBairro) {
		this.posicao = posicao;
		this.codigoBairro = codigoBairro;
		this.numeroChamados = numeroChamados;
		this.nomeBairro = nomeBairro;
	}

	@Column(name = "posicao", length = 4)
	public String getPosicao() {
		return this.posicao;
	}

	public void setPosicao(String posicao) {
		this.posicao = posicao;
	}

	@Column(name = "codigo_bairro", length = 10)
	public String getCodigoBairro() {
		return this.codigoBairro;
	}

	public void setCodigoBairro(String codigoBairro) {
		this.codigoBairro = codigoBairro;
	}

	@Column(name = "numero_chamados", length = 10)
	public String getNumeroChamados() {
		return this.numeroChamados;
	}

	public void setNumeroChamados(String numeroChamados) {
		this.numeroChamados = numeroChamados;
	}

	@Column(name = "nome_bairro", length = 100)
	public String getNomeBairro() {
		return this.nomeBairro;
	}

	public void setNomeBairro(String nomeBairro) {
		this.nomeBairro = nomeBairro;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RankingBairrosId))
			return false;
		RankingBairrosId castOther = (RankingBairrosId) other;

		return ((this.getPosicao() == castOther.getPosicao()) || (this
				.getPosicao() != null && castOther.getPosicao() != null && this
				.getPosicao().equals(castOther.getPosicao())))
				&& ((this.getCodigoBairro() == castOther.getCodigoBairro()) || (this
						.getCodigoBairro() != null
						&& castOther.getCodigoBairro() != null && this
						.getCodigoBairro().equals(castOther.getCodigoBairro())))
				&& ((this.getNumeroChamados() == castOther.getNumeroChamados()) || (this
						.getNumeroChamados() != null
						&& castOther.getNumeroChamados() != null && this
						.getNumeroChamados().equals(
								castOther.getNumeroChamados())))
				&& ((this.getNomeBairro() == castOther.getNomeBairro()) || (this
						.getNomeBairro() != null
						&& castOther.getNomeBairro() != null && this
						.getNomeBairro().equals(castOther.getNomeBairro())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getPosicao() == null ? 0 : this.getPosicao().hashCode());
		result = 37
				* result
				+ (getCodigoBairro() == null ? 0 : this.getCodigoBairro()
						.hashCode());
		result = 37
				* result
				+ (getNumeroChamados() == null ? 0 : this.getNumeroChamados()
						.hashCode());
		result = 37
				* result
				+ (getNomeBairro() == null ? 0 : this.getNomeBairro()
						.hashCode());
		return result;
	}

}
