package model;

// Generated 14/12/2013 14:42:03 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SadtId generated by hbm2java
 */
@Embeddable
public class SadtId implements java.io.Serializable {

	private Integer rpa;
	private Integer microRegiao;
	private String unidade;
	private String endereco;
	private String bairro;
	private String fone;
	private String especialidade;
	private String tipoUnidade;

	public SadtId() {
	}

	public SadtId(Integer rpa, Integer microRegiao, String unidade,
			String endereco, String bairro, String fone, String especialidade,
			String tipoUnidade) {
		this.rpa = rpa;
		this.microRegiao = microRegiao;
		this.unidade = unidade;
		this.endereco = endereco;
		this.bairro = bairro;
		this.fone = fone;
		this.especialidade = especialidade;
		this.tipoUnidade = tipoUnidade;
	}

	@Column(name = "RPA")
	public Integer getRpa() {
		return this.rpa;
	}

	public void setRpa(Integer rpa) {
		this.rpa = rpa;
	}

	@Column(name = "MICRO_REGIAO")
	public Integer getMicroRegiao() {
		return this.microRegiao;
	}

	public void setMicroRegiao(Integer microRegiao) {
		this.microRegiao = microRegiao;
	}

	@Column(name = "UNIDADE", length = 80)
	public String getUnidade() {
		return this.unidade;
	}

	public void setUnidade(String unidade) {
		this.unidade = unidade;
	}

	@Column(name = "ENDERECO", length = 80)
	public String getEndereco() {
		return this.endereco;
	}

	public void setEndereco(String endereco) {
		this.endereco = endereco;
	}

	@Column(name = "BAIRRO", length = 80)
	public String getBairro() {
		return this.bairro;
	}

	public void setBairro(String bairro) {
		this.bairro = bairro;
	}

	@Column(name = "FONE", length = 80)
	public String getFone() {
		return this.fone;
	}

	public void setFone(String fone) {
		this.fone = fone;
	}

	@Column(name = "ESPECIALIDADE", length = 80)
	public String getEspecialidade() {
		return this.especialidade;
	}

	public void setEspecialidade(String especialidade) {
		this.especialidade = especialidade;
	}

	@Column(name = "TIPO_UNIDADE", length = 80)
	public String getTipoUnidade() {
		return this.tipoUnidade;
	}

	public void setTipoUnidade(String tipoUnidade) {
		this.tipoUnidade = tipoUnidade;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SadtId))
			return false;
		SadtId castOther = (SadtId) other;

		return ((this.getRpa() == castOther.getRpa()) || (this.getRpa() != null
				&& castOther.getRpa() != null && this.getRpa().equals(
				castOther.getRpa())))
				&& ((this.getMicroRegiao() == castOther.getMicroRegiao()) || (this
						.getMicroRegiao() != null
						&& castOther.getMicroRegiao() != null && this
						.getMicroRegiao().equals(castOther.getMicroRegiao())))
				&& ((this.getUnidade() == castOther.getUnidade()) || (this
						.getUnidade() != null && castOther.getUnidade() != null && this
						.getUnidade().equals(castOther.getUnidade())))
				&& ((this.getEndereco() == castOther.getEndereco()) || (this
						.getEndereco() != null
						&& castOther.getEndereco() != null && this
						.getEndereco().equals(castOther.getEndereco())))
				&& ((this.getBairro() == castOther.getBairro()) || (this
						.getBairro() != null && castOther.getBairro() != null && this
						.getBairro().equals(castOther.getBairro())))
				&& ((this.getFone() == castOther.getFone()) || (this.getFone() != null
						&& castOther.getFone() != null && this.getFone()
						.equals(castOther.getFone())))
				&& ((this.getEspecialidade() == castOther.getEspecialidade()) || (this
						.getEspecialidade() != null
						&& castOther.getEspecialidade() != null && this
						.getEspecialidade()
						.equals(castOther.getEspecialidade())))
				&& ((this.getTipoUnidade() == castOther.getTipoUnidade()) || (this
						.getTipoUnidade() != null
						&& castOther.getTipoUnidade() != null && this
						.getTipoUnidade().equals(castOther.getTipoUnidade())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getRpa() == null ? 0 : this.getRpa().hashCode());
		result = 37
				* result
				+ (getMicroRegiao() == null ? 0 : this.getMicroRegiao()
						.hashCode());
		result = 37 * result
				+ (getUnidade() == null ? 0 : this.getUnidade().hashCode());
		result = 37 * result
				+ (getEndereco() == null ? 0 : this.getEndereco().hashCode());
		result = 37 * result
				+ (getBairro() == null ? 0 : this.getBairro().hashCode());
		result = 37 * result
				+ (getFone() == null ? 0 : this.getFone().hashCode());
		result = 37
				* result
				+ (getEspecialidade() == null ? 0 : this.getEspecialidade()
						.hashCode());
		result = 37
				* result
				+ (getTipoUnidade() == null ? 0 : this.getTipoUnidade()
						.hashCode());
		return result;
	}

}
