package model;

// Generated 14/12/2013 14:42:03 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * Solicitacoes2012Id generated by hbm2java
 */
@Embeddable
public class Solicitacoes2012Id implements java.io.Serializable {

	private Integer solicitacaoNumero;
	private String solicitacaoData;
	private String pacienteSexo;
	private Integer pacienteIdadeanos;
	private Integer pacienteIdademeses;
	private Integer bairrosaudeCodigo;
	private Integer origemchamadoCodigo;
	private String origemchamadoDescricao;
	private Integer situacaosolicitacaoCodigo;
	private String situacaosolicitacaoDescricao;
	private Integer sistemasaudeCodigo;
	private String sistemasaudeDescricao;
	private Integer motivodescarteCodigo;
	private String motivodescarteDescricao;
	private String acompanhamentoMedico;
	private String dataAcionamento;
	private String dataChegada;
	private String dataConclusao;
	private String dataRemocao;
	private Integer tipoocorrenciaCodigo;
	private String tipoocorrenciaDescricao;

	public Solicitacoes2012Id() {
	}

	public Solicitacoes2012Id(Integer solicitacaoNumero,
			String solicitacaoData, String pacienteSexo,
			Integer pacienteIdadeanos, Integer pacienteIdademeses,
			Integer bairrosaudeCodigo, Integer origemchamadoCodigo,
			String origemchamadoDescricao, Integer situacaosolicitacaoCodigo,
			String situacaosolicitacaoDescricao, Integer sistemasaudeCodigo,
			String sistemasaudeDescricao, Integer motivodescarteCodigo,
			String motivodescarteDescricao, String acompanhamentoMedico,
			String dataAcionamento, String dataChegada, String dataConclusao,
			String dataRemocao, Integer tipoocorrenciaCodigo,
			String tipoocorrenciaDescricao) {
		this.solicitacaoNumero = solicitacaoNumero;
		this.solicitacaoData = solicitacaoData;
		this.pacienteSexo = pacienteSexo;
		this.pacienteIdadeanos = pacienteIdadeanos;
		this.pacienteIdademeses = pacienteIdademeses;
		this.bairrosaudeCodigo = bairrosaudeCodigo;
		this.origemchamadoCodigo = origemchamadoCodigo;
		this.origemchamadoDescricao = origemchamadoDescricao;
		this.situacaosolicitacaoCodigo = situacaosolicitacaoCodigo;
		this.situacaosolicitacaoDescricao = situacaosolicitacaoDescricao;
		this.sistemasaudeCodigo = sistemasaudeCodigo;
		this.sistemasaudeDescricao = sistemasaudeDescricao;
		this.motivodescarteCodigo = motivodescarteCodigo;
		this.motivodescarteDescricao = motivodescarteDescricao;
		this.acompanhamentoMedico = acompanhamentoMedico;
		this.dataAcionamento = dataAcionamento;
		this.dataChegada = dataChegada;
		this.dataConclusao = dataConclusao;
		this.dataRemocao = dataRemocao;
		this.tipoocorrenciaCodigo = tipoocorrenciaCodigo;
		this.tipoocorrenciaDescricao = tipoocorrenciaDescricao;
	}

	@Column(name = "SOLICITACAO_NUMERO")
	public Integer getSolicitacaoNumero() {
		return this.solicitacaoNumero;
	}

	public void setSolicitacaoNumero(Integer solicitacaoNumero) {
		this.solicitacaoNumero = solicitacaoNumero;
	}

	@Column(name = "SOLICITACAO_DATA", length = 10)
	public String getSolicitacaoData() {
		return this.solicitacaoData;
	}

	public void setSolicitacaoData(String solicitacaoData) {
		this.solicitacaoData = solicitacaoData;
	}

	@Column(name = "PACIENTE_SEXO", length = 8)
	public String getPacienteSexo() {
		return this.pacienteSexo;
	}

	public void setPacienteSexo(String pacienteSexo) {
		this.pacienteSexo = pacienteSexo;
	}

	@Column(name = "PACIENTE_IDADEANOS")
	public Integer getPacienteIdadeanos() {
		return this.pacienteIdadeanos;
	}

	public void setPacienteIdadeanos(Integer pacienteIdadeanos) {
		this.pacienteIdadeanos = pacienteIdadeanos;
	}

	@Column(name = "PACIENTE_IDADEMESES")
	public Integer getPacienteIdademeses() {
		return this.pacienteIdademeses;
	}

	public void setPacienteIdademeses(Integer pacienteIdademeses) {
		this.pacienteIdademeses = pacienteIdademeses;
	}

	@Column(name = "BAIRROSAUDE_CODIGO")
	public Integer getBairrosaudeCodigo() {
		return this.bairrosaudeCodigo;
	}

	public void setBairrosaudeCodigo(Integer bairrosaudeCodigo) {
		this.bairrosaudeCodigo = bairrosaudeCodigo;
	}

	@Column(name = "ORIGEMCHAMADO_CODIGO")
	public Integer getOrigemchamadoCodigo() {
		return this.origemchamadoCodigo;
	}

	public void setOrigemchamadoCodigo(Integer origemchamadoCodigo) {
		this.origemchamadoCodigo = origemchamadoCodigo;
	}

	@Column(name = "ORIGEMCHAMADO_DESCRICAO", length = 20)
	public String getOrigemchamadoDescricao() {
		return this.origemchamadoDescricao;
	}

	public void setOrigemchamadoDescricao(String origemchamadoDescricao) {
		this.origemchamadoDescricao = origemchamadoDescricao;
	}

	@Column(name = "SITUACAOSOLICITACAO_CODIGO")
	public Integer getSituacaosolicitacaoCodigo() {
		return this.situacaosolicitacaoCodigo;
	}

	public void setSituacaosolicitacaoCodigo(Integer situacaosolicitacaoCodigo) {
		this.situacaosolicitacaoCodigo = situacaosolicitacaoCodigo;
	}

	@Column(name = "SITUACAOSOLICITACAO_DESCRICAO", length = 25)
	public String getSituacaosolicitacaoDescricao() {
		return this.situacaosolicitacaoDescricao;
	}

	public void setSituacaosolicitacaoDescricao(
			String situacaosolicitacaoDescricao) {
		this.situacaosolicitacaoDescricao = situacaosolicitacaoDescricao;
	}

	@Column(name = "SISTEMASAUDE_CODIGO")
	public Integer getSistemasaudeCodigo() {
		return this.sistemasaudeCodigo;
	}

	public void setSistemasaudeCodigo(Integer sistemasaudeCodigo) {
		this.sistemasaudeCodigo = sistemasaudeCodigo;
	}

	@Column(name = "SISTEMASAUDE_DESCRICAO", length = 25)
	public String getSistemasaudeDescricao() {
		return this.sistemasaudeDescricao;
	}

	public void setSistemasaudeDescricao(String sistemasaudeDescricao) {
		this.sistemasaudeDescricao = sistemasaudeDescricao;
	}

	@Column(name = "MOTIVODESCARTE_CODIGO")
	public Integer getMotivodescarteCodigo() {
		return this.motivodescarteCodigo;
	}

	public void setMotivodescarteCodigo(Integer motivodescarteCodigo) {
		this.motivodescarteCodigo = motivodescarteCodigo;
	}

	@Column(name = "MOTIVODESCARTE_DESCRICAO", length = 50)
	public String getMotivodescarteDescricao() {
		return this.motivodescarteDescricao;
	}

	public void setMotivodescarteDescricao(String motivodescarteDescricao) {
		this.motivodescarteDescricao = motivodescarteDescricao;
	}

	@Column(name = "ACOMPANHAMENTO_MEDICO", length = 3)
	public String getAcompanhamentoMedico() {
		return this.acompanhamentoMedico;
	}

	public void setAcompanhamentoMedico(String acompanhamentoMedico) {
		this.acompanhamentoMedico = acompanhamentoMedico;
	}

	@Column(name = "DATA_ACIONAMENTO", length = 20)
	public String getDataAcionamento() {
		return this.dataAcionamento;
	}

	public void setDataAcionamento(String dataAcionamento) {
		this.dataAcionamento = dataAcionamento;
	}

	@Column(name = "DATA_CHEGADA", length = 20)
	public String getDataChegada() {
		return this.dataChegada;
	}

	public void setDataChegada(String dataChegada) {
		this.dataChegada = dataChegada;
	}

	@Column(name = "DATA_CONCLUSAO", length = 20)
	public String getDataConclusao() {
		return this.dataConclusao;
	}

	public void setDataConclusao(String dataConclusao) {
		this.dataConclusao = dataConclusao;
	}

	@Column(name = "DATA_REMOCAO", length = 20)
	public String getDataRemocao() {
		return this.dataRemocao;
	}

	public void setDataRemocao(String dataRemocao) {
		this.dataRemocao = dataRemocao;
	}

	@Column(name = "TIPOOCORRENCIA_CODIGO")
	public Integer getTipoocorrenciaCodigo() {
		return this.tipoocorrenciaCodigo;
	}

	public void setTipoocorrenciaCodigo(Integer tipoocorrenciaCodigo) {
		this.tipoocorrenciaCodigo = tipoocorrenciaCodigo;
	}

	@Column(name = "TIPOOCORRENCIA_DESCRICAO", length = 10)
	public String getTipoocorrenciaDescricao() {
		return this.tipoocorrenciaDescricao;
	}

	public void setTipoocorrenciaDescricao(String tipoocorrenciaDescricao) {
		this.tipoocorrenciaDescricao = tipoocorrenciaDescricao;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Solicitacoes2012Id))
			return false;
		Solicitacoes2012Id castOther = (Solicitacoes2012Id) other;

		return ((this.getSolicitacaoNumero() == castOther
				.getSolicitacaoNumero()) || (this.getSolicitacaoNumero() != null
				&& castOther.getSolicitacaoNumero() != null && this
				.getSolicitacaoNumero()
				.equals(castOther.getSolicitacaoNumero())))
				&& ((this.getSolicitacaoData() == castOther
						.getSolicitacaoData()) || (this.getSolicitacaoData() != null
						&& castOther.getSolicitacaoData() != null && this
						.getSolicitacaoData().equals(
								castOther.getSolicitacaoData())))
				&& ((this.getPacienteSexo() == castOther.getPacienteSexo()) || (this
						.getPacienteSexo() != null
						&& castOther.getPacienteSexo() != null && this
						.getPacienteSexo().equals(castOther.getPacienteSexo())))
				&& ((this.getPacienteIdadeanos() == castOther
						.getPacienteIdadeanos()) || (this
						.getPacienteIdadeanos() != null
						&& castOther.getPacienteIdadeanos() != null && this
						.getPacienteIdadeanos().equals(
								castOther.getPacienteIdadeanos())))
				&& ((this.getPacienteIdademeses() == castOther
						.getPacienteIdademeses()) || (this
						.getPacienteIdademeses() != null
						&& castOther.getPacienteIdademeses() != null && this
						.getPacienteIdademeses().equals(
								castOther.getPacienteIdademeses())))
				&& ((this.getBairrosaudeCodigo() == castOther
						.getBairrosaudeCodigo()) || (this
						.getBairrosaudeCodigo() != null
						&& castOther.getBairrosaudeCodigo() != null && this
						.getBairrosaudeCodigo().equals(
								castOther.getBairrosaudeCodigo())))
				&& ((this.getOrigemchamadoCodigo() == castOther
						.getOrigemchamadoCodigo()) || (this
						.getOrigemchamadoCodigo() != null
						&& castOther.getOrigemchamadoCodigo() != null && this
						.getOrigemchamadoCodigo().equals(
								castOther.getOrigemchamadoCodigo())))
				&& ((this.getOrigemchamadoDescricao() == castOther
						.getOrigemchamadoDescricao()) || (this
						.getOrigemchamadoDescricao() != null
						&& castOther.getOrigemchamadoDescricao() != null && this
						.getOrigemchamadoDescricao().equals(
								castOther.getOrigemchamadoDescricao())))
				&& ((this.getSituacaosolicitacaoCodigo() == castOther
						.getSituacaosolicitacaoCodigo()) || (this
						.getSituacaosolicitacaoCodigo() != null
						&& castOther.getSituacaosolicitacaoCodigo() != null && this
						.getSituacaosolicitacaoCodigo().equals(
								castOther.getSituacaosolicitacaoCodigo())))
				&& ((this.getSituacaosolicitacaoDescricao() == castOther
						.getSituacaosolicitacaoDescricao()) || (this
						.getSituacaosolicitacaoDescricao() != null
						&& castOther.getSituacaosolicitacaoDescricao() != null && this
						.getSituacaosolicitacaoDescricao().equals(
								castOther.getSituacaosolicitacaoDescricao())))
				&& ((this.getSistemasaudeCodigo() == castOther
						.getSistemasaudeCodigo()) || (this
						.getSistemasaudeCodigo() != null
						&& castOther.getSistemasaudeCodigo() != null && this
						.getSistemasaudeCodigo().equals(
								castOther.getSistemasaudeCodigo())))
				&& ((this.getSistemasaudeDescricao() == castOther
						.getSistemasaudeDescricao()) || (this
						.getSistemasaudeDescricao() != null
						&& castOther.getSistemasaudeDescricao() != null && this
						.getSistemasaudeDescricao().equals(
								castOther.getSistemasaudeDescricao())))
				&& ((this.getMotivodescarteCodigo() == castOther
						.getMotivodescarteCodigo()) || (this
						.getMotivodescarteCodigo() != null
						&& castOther.getMotivodescarteCodigo() != null && this
						.getMotivodescarteCodigo().equals(
								castOther.getMotivodescarteCodigo())))
				&& ((this.getMotivodescarteDescricao() == castOther
						.getMotivodescarteDescricao()) || (this
						.getMotivodescarteDescricao() != null
						&& castOther.getMotivodescarteDescricao() != null && this
						.getMotivodescarteDescricao().equals(
								castOther.getMotivodescarteDescricao())))
				&& ((this.getAcompanhamentoMedico() == castOther
						.getAcompanhamentoMedico()) || (this
						.getAcompanhamentoMedico() != null
						&& castOther.getAcompanhamentoMedico() != null && this
						.getAcompanhamentoMedico().equals(
								castOther.getAcompanhamentoMedico())))
				&& ((this.getDataAcionamento() == castOther
						.getDataAcionamento()) || (this.getDataAcionamento() != null
						&& castOther.getDataAcionamento() != null && this
						.getDataAcionamento().equals(
								castOther.getDataAcionamento())))
				&& ((this.getDataChegada() == castOther.getDataChegada()) || (this
						.getDataChegada() != null
						&& castOther.getDataChegada() != null && this
						.getDataChegada().equals(castOther.getDataChegada())))
				&& ((this.getDataConclusao() == castOther.getDataConclusao()) || (this
						.getDataConclusao() != null
						&& castOther.getDataConclusao() != null && this
						.getDataConclusao()
						.equals(castOther.getDataConclusao())))
				&& ((this.getDataRemocao() == castOther.getDataRemocao()) || (this
						.getDataRemocao() != null
						&& castOther.getDataRemocao() != null && this
						.getDataRemocao().equals(castOther.getDataRemocao())))
				&& ((this.getTipoocorrenciaCodigo() == castOther
						.getTipoocorrenciaCodigo()) || (this
						.getTipoocorrenciaCodigo() != null
						&& castOther.getTipoocorrenciaCodigo() != null && this
						.getTipoocorrenciaCodigo().equals(
								castOther.getTipoocorrenciaCodigo())))
				&& ((this.getTipoocorrenciaDescricao() == castOther
						.getTipoocorrenciaDescricao()) || (this
						.getTipoocorrenciaDescricao() != null
						&& castOther.getTipoocorrenciaDescricao() != null && this
						.getTipoocorrenciaDescricao().equals(
								castOther.getTipoocorrenciaDescricao())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getSolicitacaoNumero() == null ? 0 : this
						.getSolicitacaoNumero().hashCode());
		result = 37
				* result
				+ (getSolicitacaoData() == null ? 0 : this.getSolicitacaoData()
						.hashCode());
		result = 37
				* result
				+ (getPacienteSexo() == null ? 0 : this.getPacienteSexo()
						.hashCode());
		result = 37
				* result
				+ (getPacienteIdadeanos() == null ? 0 : this
						.getPacienteIdadeanos().hashCode());
		result = 37
				* result
				+ (getPacienteIdademeses() == null ? 0 : this
						.getPacienteIdademeses().hashCode());
		result = 37
				* result
				+ (getBairrosaudeCodigo() == null ? 0 : this
						.getBairrosaudeCodigo().hashCode());
		result = 37
				* result
				+ (getOrigemchamadoCodigo() == null ? 0 : this
						.getOrigemchamadoCodigo().hashCode());
		result = 37
				* result
				+ (getOrigemchamadoDescricao() == null ? 0 : this
						.getOrigemchamadoDescricao().hashCode());
		result = 37
				* result
				+ (getSituacaosolicitacaoCodigo() == null ? 0 : this
						.getSituacaosolicitacaoCodigo().hashCode());
		result = 37
				* result
				+ (getSituacaosolicitacaoDescricao() == null ? 0 : this
						.getSituacaosolicitacaoDescricao().hashCode());
		result = 37
				* result
				+ (getSistemasaudeCodigo() == null ? 0 : this
						.getSistemasaudeCodigo().hashCode());
		result = 37
				* result
				+ (getSistemasaudeDescricao() == null ? 0 : this
						.getSistemasaudeDescricao().hashCode());
		result = 37
				* result
				+ (getMotivodescarteCodigo() == null ? 0 : this
						.getMotivodescarteCodigo().hashCode());
		result = 37
				* result
				+ (getMotivodescarteDescricao() == null ? 0 : this
						.getMotivodescarteDescricao().hashCode());
		result = 37
				* result
				+ (getAcompanhamentoMedico() == null ? 0 : this
						.getAcompanhamentoMedico().hashCode());
		result = 37
				* result
				+ (getDataAcionamento() == null ? 0 : this.getDataAcionamento()
						.hashCode());
		result = 37
				* result
				+ (getDataChegada() == null ? 0 : this.getDataChegada()
						.hashCode());
		result = 37
				* result
				+ (getDataConclusao() == null ? 0 : this.getDataConclusao()
						.hashCode());
		result = 37
				* result
				+ (getDataRemocao() == null ? 0 : this.getDataRemocao()
						.hashCode());
		result = 37
				* result
				+ (getTipoocorrenciaCodigo() == null ? 0 : this
						.getTipoocorrenciaCodigo().hashCode());
		result = 37
				* result
				+ (getTipoocorrenciaDescricao() == null ? 0 : this
						.getTipoocorrenciaDescricao().hashCode());
		return result;
	}

}
