package model;

// Generated 14/12/2013 01:12:12 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Spa generated by hbm2java
 */
@Entity
@Table(name = "spa", catalog = "saude_rec")
public class Spa implements java.io.Serializable {

	private SpaId id;

	public Spa() {
	}

	public Spa(SpaId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "rpa", column = @Column(name = "RPA")),
			@AttributeOverride(name = "microRegiao", column = @Column(name = "MICRO_REGIAO")),
			@AttributeOverride(name = "cnes", column = @Column(name = "CNES")),
			@AttributeOverride(name = "unidade", column = @Column(name = "UNIDADE", length = 80)),
			@AttributeOverride(name = "endereco", column = @Column(name = "ENDERECO", length = 80)),
			@AttributeOverride(name = "bairro", column = @Column(name = "BAIRRO", length = 80)),
			@AttributeOverride(name = "fone", column = @Column(name = "FONE", length = 15)),
			@AttributeOverride(name = "especialidades", column = @Column(name = "ESPECIALIDADES", length = 15)),
			@AttributeOverride(name = "latitude", column = @Column(name = "LATITUDE", length = 15)),
			@AttributeOverride(name = "longitude", column = @Column(name = "LONGITUDE", length = 15)) })
	public SpaId getId() {
		return this.id;
	}

	public void setId(SpaId id) {
		this.id = id;
	}

}
