package model;

// Generated 14/12/2013 01:12:12 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Viatura2012 generated by hbm2java
 */
@Entity
@Table(name = "viatura2012", catalog = "saude_rec")
public class Viatura2012 implements java.io.Serializable {

	private Viatura2012Id id;

	public Viatura2012() {
	}

	public Viatura2012(Viatura2012Id id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "viaturaCodigo", column = @Column(name = "VIATURA_CODIGO")),
			@AttributeOverride(name = "viaturaDescricao", column = @Column(name = "VIATURA_DESCRICAO", length = 30)),
			@AttributeOverride(name = "distritosanitarioCodigo", column = @Column(name = "DISTRITOSANITARIO_CODIGO")),
			@AttributeOverride(name = "tipoviaturaCodigo", column = @Column(name = "TIPOVIATURA_CODIGO")),
			@AttributeOverride(name = "tipoviaturaDescricao", column = @Column(name = "TIPOVIATURA_DESCRICAO", length = 30)) })
	public Viatura2012Id getId() {
		return this.id;
	}

	public void setId(Viatura2012Id id) {
		this.id = id;
	}

}
