package model;

// Generated 14/12/2013 01:12:12 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * Viatura2012Id generated by hbm2java
 */
@Embeddable
public class Viatura2012Id implements java.io.Serializable {

	private Integer viaturaCodigo;
	private String viaturaDescricao;
	private Integer distritosanitarioCodigo;
	private Integer tipoviaturaCodigo;
	private String tipoviaturaDescricao;

	public Viatura2012Id() {
	}

	public Viatura2012Id(Integer viaturaCodigo, String viaturaDescricao,
			Integer distritosanitarioCodigo, Integer tipoviaturaCodigo,
			String tipoviaturaDescricao) {
		this.viaturaCodigo = viaturaCodigo;
		this.viaturaDescricao = viaturaDescricao;
		this.distritosanitarioCodigo = distritosanitarioCodigo;
		this.tipoviaturaCodigo = tipoviaturaCodigo;
		this.tipoviaturaDescricao = tipoviaturaDescricao;
	}

	@Column(name = "VIATURA_CODIGO")
	public Integer getViaturaCodigo() {
		return this.viaturaCodigo;
	}

	public void setViaturaCodigo(Integer viaturaCodigo) {
		this.viaturaCodigo = viaturaCodigo;
	}

	@Column(name = "VIATURA_DESCRICAO", length = 30)
	public String getViaturaDescricao() {
		return this.viaturaDescricao;
	}

	public void setViaturaDescricao(String viaturaDescricao) {
		this.viaturaDescricao = viaturaDescricao;
	}

	@Column(name = "DISTRITOSANITARIO_CODIGO")
	public Integer getDistritosanitarioCodigo() {
		return this.distritosanitarioCodigo;
	}

	public void setDistritosanitarioCodigo(Integer distritosanitarioCodigo) {
		this.distritosanitarioCodigo = distritosanitarioCodigo;
	}

	@Column(name = "TIPOVIATURA_CODIGO")
	public Integer getTipoviaturaCodigo() {
		return this.tipoviaturaCodigo;
	}

	public void setTipoviaturaCodigo(Integer tipoviaturaCodigo) {
		this.tipoviaturaCodigo = tipoviaturaCodigo;
	}

	@Column(name = "TIPOVIATURA_DESCRICAO", length = 30)
	public String getTipoviaturaDescricao() {
		return this.tipoviaturaDescricao;
	}

	public void setTipoviaturaDescricao(String tipoviaturaDescricao) {
		this.tipoviaturaDescricao = tipoviaturaDescricao;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Viatura2012Id))
			return false;
		Viatura2012Id castOther = (Viatura2012Id) other;

		return ((this.getViaturaCodigo() == castOther.getViaturaCodigo()) || (this
				.getViaturaCodigo() != null
				&& castOther.getViaturaCodigo() != null && this
				.getViaturaCodigo().equals(castOther.getViaturaCodigo())))
				&& ((this.getViaturaDescricao() == castOther
						.getViaturaDescricao()) || (this.getViaturaDescricao() != null
						&& castOther.getViaturaDescricao() != null && this
						.getViaturaDescricao().equals(
								castOther.getViaturaDescricao())))
				&& ((this.getDistritosanitarioCodigo() == castOther
						.getDistritosanitarioCodigo()) || (this
						.getDistritosanitarioCodigo() != null
						&& castOther.getDistritosanitarioCodigo() != null && this
						.getDistritosanitarioCodigo().equals(
								castOther.getDistritosanitarioCodigo())))
				&& ((this.getTipoviaturaCodigo() == castOther
						.getTipoviaturaCodigo()) || (this
						.getTipoviaturaCodigo() != null
						&& castOther.getTipoviaturaCodigo() != null && this
						.getTipoviaturaCodigo().equals(
								castOther.getTipoviaturaCodigo())))
				&& ((this.getTipoviaturaDescricao() == castOther
						.getTipoviaturaDescricao()) || (this
						.getTipoviaturaDescricao() != null
						&& castOther.getTipoviaturaDescricao() != null && this
						.getTipoviaturaDescricao().equals(
								castOther.getTipoviaturaDescricao())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getViaturaCodigo() == null ? 0 : this.getViaturaCodigo()
						.hashCode());
		result = 37
				* result
				+ (getViaturaDescricao() == null ? 0 : this
						.getViaturaDescricao().hashCode());
		result = 37
				* result
				+ (getDistritosanitarioCodigo() == null ? 0 : this
						.getDistritosanitarioCodigo().hashCode());
		result = 37
				* result
				+ (getTipoviaturaCodigo() == null ? 0 : this
						.getTipoviaturaCodigo().hashCode());
		result = 37
				* result
				+ (getTipoviaturaDescricao() == null ? 0 : this
						.getTipoviaturaDescricao().hashCode());
		return result;
	}

}
