package model;

// Generated 08/12/2013 19:30:13 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Distritos2011 generated by hbm2java
 */
@Entity
@Table(name = "distritos_2011", catalog = "saude_rec")
public class Distritos2011 implements java.io.Serializable {

	private Distritos2011Id id;

	public Distritos2011() {
	}

	public Distritos2011(Distritos2011Id id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "distritosanitarioCodigo", column = @Column(name = "distritosanitario_codigo")),
			@AttributeOverride(name = "distritosanitarioDescricao", column = @Column(name = "distritosanitario_descricao", length = 30)),
			@AttributeOverride(name = "municipioCodigo", column = @Column(name = "municipio_codigo")),
			@AttributeOverride(name = "municipioDescricao", column = @Column(name = "municipio_descricao", length = 25)),
			@AttributeOverride(name = "regiao", column = @Column(name = "regiao")) })
	public Distritos2011Id getId() {
		return this.id;
	}

	public void setId(Distritos2011Id id) {
		this.id = id;
	}

}
